baseurl: /smart2-doc
pygments: true
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
